import Vue from 'vue'
//引入element-ui 组件
import 'element-ui/lib/theme-chalk/index.css';
import {Button,Icon,Input,Radio,Checkbox,Link,Divider} from 'element-ui';
Vue.use(Button);
Vue.use(Input);
Vue.use(Radio);
Vue.use(Checkbox);
Vue.use(Icon);
Vue.use(Link);
Vue.use(Divider);
import {Menu,MenuItem,Submenu,Container,Header,Main,Aside,TableColumn,MenuItemGroup,Table} from 'element-ui';
Vue.use(Table);
Vue.use(MenuItemGroup);
Vue.use(TableColumn);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Header);
Vue.use(Container);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
import {Carousel,CarouselItem,Tabs,TabPane,Card,Breadcrumb,BreadcrumbItem} from 'element-ui';
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Card);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);